unbind C-b

set-option -g prefix C-a
set -g extended-keys on
set -g mouse on
setw -g mode-keys vi

bind -n C-PageUp previous-window
bind -n C-PageDown next-window
bind -n C-t new-window
bind -n S-Left swap-window -d -t -1
bind -n S-Right swap-window -d -t +1

bind-key C-a send-prefix
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
